export const SET_POSTER_ACTION = "POSTER::SET_POSTER_ACTION";
export const SET_ALL_POSTER_ACTION = "POSTER::SET_ALL_POSTER_ACTION";
export const LOADING_POSTER_ACTION = "POSTER::LOADING_POSTER_ACTION";
